In [1]:
import pandas as pd
s=pd.Series([10,20,30],index=["a","b","c"])
print(s)

data={
    "Name":["Alice","Bob","John Dea"],
    "Age":[25,56,32]
}
df=pd.DataFrame(data)
print(df)

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
col_name=["sepal_length","sepal_width","petal_length","petal_width","class"]
df=pd.read_csv(url,header=None,names=col_name,index_col=False)
print(df.head())
print(df.info())

a    10
b    20
c    30
dtype: int64
       Name  Age
0     Alice   25
1       Bob   56
2  John Dea   32
   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   class         150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB
None

Pandas vs NumPy - Which one to use and When?
Dimension > 2: Use NumPy
Use NumPy (ndarray) when your 2-D data is essentially a numeric matrix and you need fast, memory-efficient numerical work (linear algebra, broadcasting, heavy elementwise operations).
Use pandas (DataFrame) when your 2-D data is a table i.e., columns with names, mixed dtypes, missing values, need for grouping/joins/time-series/CSV/Excel IO or easy selection by column name

Will Pandas work when data is larger than memory?
Since Pandas loads the entire dataset into memory. if data is larger than the main memory Here are practical approaches:
1. Dask: A library that extends pandas with parallel computing and chunked processing.
2. Polars: A fast DataFrame library written in Rust, with lazy execution and streaming.
3. "PySpark:" A distributed big-data engine. PySpark splits the dataset into chunks (partitions) and processes them sequentially or in parallel - only a small chunk is in memory at a time.

1. What is a DataFrame?
A DataFrame is a two-dimensional, labeled data structure that stores data in rows and columns, allowing each column to hold values of different data types. A data structure is a way of organizing, storing, and managing data in a computer so that it can be used efficiently.
It is designed for handling and analyzing structured (tabular) data efficiently.
A DataFrame is:
Two-dimensional: Data is arranged in rows and columns.
Labeled: Each row has an index (like row numbers), and each column has a name.
Flexible: Can store different data types in different columns (numbers, text, dates, etc.).
Mutable: You can change, add, or delete rows and columns anytime.

In [ ]:
import pandas as pd
import numpy as np

data={
    'Name':['Amit','Anand','Akash'],
    'Age':[25,26,28],
    'City':['Mumbai','Delhi','Patna']
}
df=pd.DataFrame(data)
print(df.head())
df1=pd.DataFrame(data,index=None,columns=None,dtype=None,copy=False)
print(df1)
data=[
    ['Amit', 25, 'Mumbai'],
    ['Anand', 28, 'Delhi'],
    ['Akash', 30, 'Patna']
]
df=pd.DataFrame(data,columns=['Name','Age','City'])
print(df)
arr=np.array([['Amit', 25, 'Mumbai'],
['Anand', 28, 'Delhi'],
['Akash', 30, 'Patna']])
print(np.shape(arr))

name=pd.Series(['Amit','Anand','Akash'])
age=pd.Series([25,26,28])
city=pd.Series(['Mumbai','Delhi','Patna'])

df=pd.DataFrame({'Name':name,'Age':age,'City':city})
print(df)

    Name  Age    City
0   Amit   25  Mumbai
1  Anand   26   Delhi
2  Akash   28   Patna
    Name  Age    City
0   Amit   25  Mumbai
1  Anand   26   Delhi
2  Akash   28   Patna
    Name  Age    City
0   Amit   25  Mumbai
1  Anand   28   Delhi
2  Akash   30   Patna
(3, 3)
    Name  Age    City
0   Amit   25  Mumbai
1  Anand   26   Delhi
2  Akash   28   Patna

From CSV / EXCEL FILE

In [17]:
! pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [18]:


df=pd.read_csv("dummy_data_csv.csv")
print(df)
df=pd.read_csv("dummy_data_tsv.tsv",sep='\t')
print(df)
df=pd.read_excel("dummy_data_excel.xlsx")
print(df.head())

      Name  Age     City  Salary
0     Amit   25    Patna   70000
1    Akash   30  Lucknow   80000
2     Aman   35    Delhi   75000
3   Manish   28   Jaipur   72000
4  Peeyush   32   Ranchi   78000
      Name  Age     City  Salary
0     Amit   25    Patna   70000
1    Akash   30  Lucknow   80000
2     Aman   35    Delhi   75000
3   Manish   28   Jaipur   72000
4  Peeyush   32   Ranchi   78000
      Name  Age     City  Salary
0     Amit   25    Patna   70000
1    Akash   30  Lucknow   80000
2     Aman   35    Delhi   75000
3   Manish   28   Jaipur   72000
4  Peeyush   32   Ranchi   78000

From URL

In [19]:
url="https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df=pd.read_csv(url)
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
url="https://jsonplaceholder.typicode.com/users"
df=pd.read_json(url)
print(df.head())

   id              name   username                      email  \
0   1     Leanne Graham       Bret          Sincere@april.biz
1   2      Ervin Howell  Antonette          Shanna@melissa.tv
2   3  Clementine Bauch   Samantha         Nathan@yesenia.net
3   4  Patricia Lebsack   Karianne  Julianne.OConner@kory.org
4   5  Chelsey Dietrich     Kamren   Lucio_Hettinger@annie.ca

                                             address                  phone  \
0  {'street': 'Kulas Light', 'suite': 'Apt. 556',...  1-770-736-8031 x56442
1  {'street': 'Victor Plains', 'suite': 'Suite 87...    010-692-6593 x09125
2  {'street': 'Douglas Extension', 'suite': 'Suit...         1-463-123-4447
3  {'street': 'Hoeger Mall', 'suite': 'Apt. 692',...      493-170-9623 x156
4  {'street': 'Skiles Walks', 'suite': 'Suite 351...          (254)954-1289

         website                                            company
0  hildegard.org  {'name': 'Romaguera-Crona', 'catchPhrase': 'Mu...
1  anastasia.net  {'name': 'Deckow-Crist', 'catchPhrase': 'Proac...
2    ramiro.info  {'name': 'Romaguera-Jacobson', 'catchPhrase': ...
3       kale.biz  {'name': 'Robel-Corkery', 'catchPhrase': 'Mult...
4   demarco.info  {'name': 'Keebler LLC', 'catchPhrase': 'User-c...

In [21]:
! pip install lxml

Defaulting to user installation because normal site-packages is not writeable
Collecting lxml
  Downloading lxml-6.0.2-cp314-cp314-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp314-cp314-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.1 MB 5.9 MB/s eta 0:00:01
   ------------------------- -------------- 2.6/4.1 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 4.1/4.1 MB 9.7 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.2

In [33]:
! pip install requests

Defaulting to user installation because normal site-packages is not writeable
Collecting requests
  Downloading requests-2.33.0-py3-none-any.whl.metadata (5.1 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.6-cp314-cp314-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.33.0-py3-none-any.whl (65 kB)
Downloading charset_normalizer-3.4.6-cp314-cp314-win_amd64.whl (154 kB)
Downloading idna-3.11-py3-none-any.whl (71 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests

   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Successfully installed certifi-2026.2.25 charset_normalizer-3.4.6 idna-3.11 requests-2.33.0 urllib3-2.6.3

In [40]:
url="https://en.wikipedia.org/wiki/Indian_Institutes_of_Information_Technology"
tables = pd.read_html(url)
len(tables)

HTTPError: HTTP Error 403: Forbidden

Basic Operation in Pandas

In [6]:
import pandas as pd

data={
    'Name':['Amit','Anand','Akash'],
    'Age':[25,26,28],
    'City':['Mumbai','Delhi','Patna']
}
df=pd.DataFrame(data)
print(df)
print(df.shape)
print(len(df))
print(df.dtypes)

    Name  Age    City
0   Amit   25  Mumbai
1  Anand   26   Delhi
2  Akash   28   Patna
(3, 3)
3
Name      str
Age     int64
City      str
dtype: object

In [ ]:
# reduce memory consumed for age attribute
df['Age']=df['Age'].astype('int32')
df['City']=df['City'].astype('string')
print(df.dtypes)
df.columns
df.index

Name       str
Age      int32
City    string
dtype: object

RangeIndex(start=0, stop=3, step=1)

In [36]:
from numpy.random import randint as ri
data=ri(20,30,25).reshape(5,5)
print(data)
row_label=['A','B','C','D','E']
col_name=['U','V','W','X','Y']
df=pd.DataFrame(data,index=row_label,columns=col_name)
print(df)
print(df.describe())
print(df.index)
print(df.columns)
df2=df
print(df2)

[[28 22 21 21 27]
 [27 26 23 25 26]
 [24 29 29 22 24]
 [21 23 29 21 26]
 [20 27 26 28 29]]
    U   V   W   X   Y
A  28  22  21  21  27
B  27  26  23  25  26
C  24  29  29  22  24
D  21  23  29  21  26
E  20  27  26  28  29
               U          V          W         X         Y
count   5.000000   5.000000   5.000000   5.00000   5.00000
mean   24.000000  25.400000  25.600000  23.40000  26.40000
std     3.535534   2.880972   3.577709   3.04959   1.81659
min    20.000000  22.000000  21.000000  21.00000  24.00000
25%    21.000000  23.000000  23.000000  21.00000  26.00000
50%    24.000000  26.000000  26.000000  22.00000  26.00000
75%    27.000000  27.000000  29.000000  25.00000  27.00000
max    28.000000  29.000000  29.000000  28.00000  29.00000
Index(['A', 'B', 'C', 'D', 'E'], dtype='str')
Index(['U', 'V', 'W', 'X', 'Y'], dtype='str')
    U   V   W   X   Y
A  28  22  21  21  27
B  27  26  23  25  26
C  24  29  29  22  24
D  21  23  29  21  26
E  20  27  26  28  29

In [20]:
print(df[['X','Y']])

    X   Y
A  24  24
B  25  20
C  22  24
D  27  29
E  25  26

Delete Row and Column

In [38]:
print(df.drop('B'))
print(df.drop('X',axis=1))
df1=df
# df1.drop('U',axis=1,inplace=True)

    U   V   W   X   Y
A  28  22  21  21  27
C  24  29  29  22  24
D  21  23  29  21  26
E  20  27  26  28  29
    U   V   W   Y
A  28  22  21  27
B  27  26  23  26
C  24  29  29  24
D  21  23  29  26
E  20  27  26  29

Selecting/Indexing Rows

In [53]:
df.head()
df2.head()
print(df2.loc['A'])
print(df2.iloc[2])
print(df2)
print(df2.loc[['A','D']])
print(df2.iloc[[1,4]])
print(df2.loc['A':'C'])
print(df2.iloc[1:3])

U    28
V    22
W    21
X    21
Y    27
Name: A, dtype: int32
U    24
V    29
W    29
X    22
Y    24
Name: C, dtype: int32
    U   V   W   X   Y
A  28  22  21  21  27
B  27  26  23  25  26
C  24  29  29  22  24
D  21  23  29  21  26
E  20  27  26  28  29
    U   V   W   X   Y
A  28  22  21  21  27
D  21  23  29  21  26
    U   V   W   X   Y
B  27  26  23  25  26
E  20  27  26  28  29
    U   V   W   X   Y
A  28  22  21  21  27
B  27  26  23  25  26
C  24  29  29  22  24
    U   V   W   X   Y
B  27  26  23  25  26
C  24  29  29  22  24

In [60]:
# Subnetting
print(df2.loc['A','Y'])
print(df2.iloc[0,2])
df2

27
21

    U   V   W   X   Y
A  28  22  21  21  27
B  27  26  23  25  26
C  24  29  29  22  24
D  21  23  29  21  26
E  20  27  26  28  29

In [63]:
# adding row to a dataframe
df2.loc['F']=[34,56,78,56,89]
print(df2)

    U   V   W   X   Y
A  28  22  21  21  27
B  27  26  23  25  26
C  24  29  29  22  24
D  21  23  29  21  26
E  20  27  26  28  29
F  34  56  78  56  89

In [31]:
# split
# adding new col
# rename the index of a dataframe
# Rename the col of a dataframe 
import numpy as np
matrix_data = np.matrix('22,160,70;42,170,80;30,175,90;35,160,70;25,140,70')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight'] # 'Height(Cm)', 'Weight(Kg)
df=pd.DataFrame(matrix_data,index=row_label,columns=column_headings)
print(df)
df.loc['F']=[21,170,60]
df['BMI']=df['Weight']/(df['Height']/100)**2
df['Proffession']="Student Teacher Engineer Doctor Nurse Student".split()
df.columns=['age', 'height', 'weight','bmi','proffession']
df.index=[0,1,2,3,4,5]

NameError: name 'row_label' is not defined

In [98]:
df[df['height']>160]
df2.reset_index(inplace=True)

Advanced Operation in Pandas

In [50]:
import pandas as pd
import numpy as np
df=pd.DataFrame(
    {
        'A':[1,2,np.nan,3],
        'B':[5,np.nan,6,np.nan],
        'C':[np.nan,7,8,9]
    }
)
df['Country']="IN US ENG JP".split()
df.set_index('Country',inplace=True)
df.isna()
df.notna()

             A      B      C
Country
IN        True   True  False
US        True  False   True
ENG      False   True   True
JP        True  False   True

Handling NAN Value

In [46]:
df=df=pd.DataFrame(
    {
        'A':[1,2,np.nan,3],
        'B':[np.nan,np.nan,6,np.nan],
        'C':[np.nan,7,8,9]
    }
)
df.loc["D"] = [1, 2, 3]
df.dropna()
df.dropna(axis=1)
# minimum 2 null value
df.dropna(axis=0,thresh=2)
# Filling a nan box with a average value of the row
df.fillna(value=df['A'].mean())

      A     B     C
0  1.00  1.75  1.75
1  2.00  1.75  7.00
2  1.75  6.00  8.00
3  3.00  1.75  9.00
D  1.00  2.00  3.00

CATEGORICAL OPERATION

In [54]:
# Memory Optimazation
df.info()
df['C']=df['C'].astype('float32')
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, IN to JP
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      float64
 1   B       2 non-null      float64
 2   C       3 non-null      float64
dtypes: float64(3)
memory usage: 300.0+ bytes
<class 'pandas.DataFrame'>
Index: 4 entries, IN to JP
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      float64
 1   B       2 non-null      float64
 2   C       3 non-null      float32
dtypes: float32(1), float64(2)
memory usage: 284.0+ bytes

GROUPBY

In [63]:
data={'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
      'Person': ['Aman', 'Ankit', 'Aditya', 'Anjali', 'Ankita', 'Ayush'],
      'Sales': [200,120, 340, 124, 243,350]}
df=pd.DataFrame(data)
df.groupby('Company').Sales.mean()
df.groupby('Company').Sales.sum()
df.groupby('Company').describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

Aggregate Function

In [65]:
df['Sales'].mean()
df['Sales'].quantile(0.5)

np.float64(221.5)

Concatinate

In [76]:
import pandas as pd

# df1 (keeping columns consistent in English)
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3']
}, index=[0, 1, 2, 3])


df2 = pd.DataFrame({
    'A': ['A4', 'A5', 'A6', 'A7'],
    'B': ['B4', 'B5', 'B6', 'B7'],
    'C': ['C4', 'C5', 'C6', 'C7'],
    'D': ['D4', 'D5', 'D6', 'D7']
}, index=[4, 5, 6, 7])


df3 = pd.DataFrame({
    'A': ['A8', 'A9', 'A10', 'A11'],
    'B': ['B8', 'B9', 'B10', 'B11'],
    'C': ['C8', 'C9', 'C10', 'C11'],
    'D': ['D8', 'D9', 'D10', 'D11']
}, index=[8, 9, 10, 11])  
df_concat=pd.concat([df1,df2,df3],axis=1)
print(df_concat)
df_concat.fillna(-1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

     A   B   C   D   A   B   C   D    A    B    C    D
0   A0  B0  C0  D0  -1  -1  -1  -1   -1   -1   -1   -1
1   A1  B1  C1  D1  -1  -1  -1  -1   -1   -1   -1   -1
2   A2  B2  C2  D2  -1  -1  -1  -1   -1   -1   -1   -1
3   A3  B3  C3  D3  -1  -1  -1  -1   -1   -1   -1   -1
4   -1  -1  -1  -1  A4  B4  C4  D4   -1   -1   -1   -1
5   -1  -1  -1  -1  A5  B5  C5  D5   -1   -1   -1   -1
6   -1  -1  -1  -1  A6  B6  C6  D6   -1   -1   -1   -1
7   -1  -1  -1  -1  A7  B7  C7  D7   -1   -1   -1   -1
8   -1  -1  -1  -1  -1  -1  -1  -1   A8   B8   C8   D8
9   -1  -1  -1  -1  -1  -1  -1  -1   A9   B9   C9   D9
10  -1  -1  -1  -1  -1  -1  -1  -1  A10  B10  C10  D10
11  -1  -1  -1  -1  -1  -1  -1  -1  A11  B11  C11  D11

Merge
merge() is used to combine two DataFrames based on common columns or indices, similar to SQL joins.

In [79]:
right = pd.DataFrame({
    'key1': ['K0', 'K1', 'K1', 'K2'],
    'key2': ['K0', 'K0', 'K0', 'K0'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3']
})
left = pd.DataFrame({
    'key1': ['K0', 'K0', 'K1', 'K2'],
    'key2': ['K0', 'K1', 'K0', 'K1'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']
})

pd.merge(right,left,on=['key1','key2'])
pd.merge(right,left,on=['key1','key2'],how='right')

  key1 key2    C    D   A   B
0   K0   K0   C0   D0  A0  B0
1   K0   K1  NaN  NaN  A1  B1
2   K1   K0   C1   D1  A2  B2
3   K1   K0   C2   D2  A2  B2
4   K2   K1  NaN  NaN  A3  B3

Date and Time

In [8]:
import pandas as pd
data = {
    "model_name": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost",
        "LightGBM",
        "KNN",
        "Naive Bayes",
        "SVM",
        "CNN",
        "LSTM"
    ],
    "execution_time": [0.5, 0.8, 2.3, 3.1, 2.8, 1.2, 0.6, 1.9, 4.5, 5.0],  # seconds
    "model_size": [2.3, 5.6, 45.2, 60.1, 55.8, 8.4, 1.2, 12.3, 120.5, 150.7],  # MB
    "accuracy": [0.82, 0.78, 0.89, 0.91, 0.90, 0.76, 0.74, 0.88, 0.93, 0.92],
    "f1_score": [0.80, 0.75, 0.87, 0.90, 0.89, 0.74, 0.72, 0.86, 0.92, 0.91],
    "precision": [0.81, 0.76, 0.88, 0.91, 0.90, 0.75, 0.73, 0.87, 0.93, 0.92],
    "recall": [0.79, 0.74, 0.86, 0.89, 0.88, 0.73, 0.71, 0.85, 0.91, 0.90],
}
df=pd.DataFrame(data)
def testframe(x):
    model_name="_".join(x.split())
    model_name=model_name.lower()
    return model_name
# Apply()
df['model_name'].apply(testframe)
print(df)
df["model_name"].map(testframe)

            model_name  execution_time  model_size  accuracy  f1_score  \
0  Logistic Regression             0.5         2.3      0.82      0.80
1        Decision Tree             0.8         5.6      0.78      0.75
2        Random Forest             2.3        45.2      0.89      0.87
3              XGBoost             3.1        60.1      0.91      0.90
4             LightGBM             2.8        55.8      0.90      0.89
5                  KNN             1.2         8.4      0.76      0.74
6          Naive Bayes             0.6         1.2      0.74      0.72
7                  SVM             1.9        12.3      0.88      0.86
8                  CNN             4.5       120.5      0.93      0.92
9                 LSTM             5.0       150.7      0.92      0.91

   precision  recall
0       0.81    0.79
1       0.76    0.74
2       0.88    0.86
3       0.91    0.89
4       0.90    0.88
5       0.75    0.73
6       0.73    0.71
7       0.87    0.85
8       0.93    0.91
9       0.92    0.90

0    logistic_regression
1          decision_tree
2          random_forest
3                xgboost
4               lightgbm
5                    knn
6            naive_bayes
7                    svm
8                    cnn
9                   lstm
Name: model_name, dtype: str

In [11]:
# convert the execution time from sec to mili second
df["execution_time"].apply(lambda x:x*1000)
df["model_score"]=(
    0.8*df["f1_score"]+
    0.1*(1/df["execution_time"])+
    0.1*(1/df["model_size"])  
)
df

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall,model_score
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79,0.883478
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74,0.742857
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86,0.741691
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89,0.753922
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88,0.749506
5,KNN,1.2,8.4,0.76,0.74,0.75,0.73,0.687238
6,Naive Bayes,0.6,1.2,0.74,0.72,0.73,0.71,0.826000
7,SVM,1.9,12.3,0.88,0.86,0.87,0.85,0.748762
8,CNN,4.5,120.5,0.93,0.92,0.93,0.91,0.759052
9,LSTM,5.0,150.7,0.92,0.91,0.92,0.90,0.748664

Apply Built in Functions

In [16]:
import math
print(df['model_name'].apply(len))
print(df['precision'].apply(math.sqrt))
df.sort_values(by="model_score", ascending=False)

0    19
1    13
2    13
3     7
4     8
5     3
6    11
7     3
8     3
9     4
Name: model_name, dtype: int64
0    0.900000
1    0.871780
2    0.938083
3    0.953939
4    0.948683
5    0.866025
6    0.854400
7    0.932738
8    0.964365
9    0.959166
Name: precision, dtype: float64

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall,model_score
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79,0.883478
6,Naive Bayes,0.6,1.2,0.74,0.72,0.73,0.71,0.826000
8,CNN,4.5,120.5,0.93,0.92,0.93,0.91,0.759052
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89,0.753922
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88,0.749506
7,SVM,1.9,12.3,0.88,0.86,0.87,0.85,0.748762
9,LSTM,5.0,150.7,0.92,0.91,0.92,0.90,0.748664
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74,0.742857
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86,0.741691
5,KNN,1.2,8.4,0.76,0.74,0.75,0.73,0.687238

DATE AND TIME

In [26]:
# create a timestamp from a string data
pd.Timestamp("2025-08-18 14:30:15")
pd.to_datetime(["2025-08-18","2025-08-19"])
ts1=pd.date_range("2025-08-18 14:30:15",periods=5)
start=pd.Timestamp(2025,1,1)
end=pd.Timestamp(2025,1,10)
pd.date_range(start,end)
print(start)
start+pd.Timedelta(days=4,hours=4)

2025-01-01 00:00:00

Timestamp('2025-01-05 04:00:00')

In [32]:
data = {
    "date": ["2025-08-21", "2025-08-22", "2025-08-23"],
    "value": [10, 20, 30]
}
df=pd.DataFrame(data)
df["date"]=pd.to_datetime(df["date"])
df.info()
df.memory_usage()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      datetime64[us]
 1   value   3 non-null      int64
dtypes: datetime64[us](1), int64(1)
memory usage: 180.0 bytes

Index    132
date      24
value     24
dtype: int64

Operation on Date and Time

In [40]:
t=pd.Series(pd.date_range('2025-01-01',periods=5,freq='D'))
t
h=pd.Series(pd.Timedelta(hours=i) for i in range(5))
h
df=pd.DataFrame({
    'A':t,
    'B':h
})
df['C']=df['A']+df['B']
df

           A               B                   C
0 2025-01-01 0 days 00:00:00 2025-01-01 00:00:00
1 2025-01-02 0 days 01:00:00 2025-01-02 01:00:00
2 2025-01-03 0 days 02:00:00 2025-01-03 02:00:00
3 2025-01-04 0 days 03:00:00 2025-01-04 03:00:00
4 2025-01-05 0 days 04:00:00 2025-01-05 04:00:00

In [46]:
# filter
data = {
    'Event': ['A', 'B', 'C', 'D', 'E'],
    'Date': pd.to_datetime([
        '2025-08-18', '2025-08-19', '2025-08-20',
        '2025-08-21', '2025-08-22'
    ])
}
df=pd.DataFrame(data)
df[df['Date']=="2025-08-22"]
df[(df['Date']>="2025-08-20") & (df['Date']<="2025-08-22")]
# filter by day of weeks
df[df['Date'].dt.day_of_week==0]

  Event       Date
0     A 2025-08-18

In [53]:
# benefit of datetimeindex over regular common index
data={
    'Date':pd.date_range('2025-01-02',periods=5,freq='D'),
    'Value':[10,20,30,40,50]
}
df=pd.DataFrame(data)
df_col=df.drop(columns='Date')
print(df)
df_col.index=data['Date']
print(df_col)

# filtering a specific data
df_col.loc["2025-01-03"]
# Slicing
df_col["2025-01-03":"2025-01-05"]

        Date  Value
0 2025-01-02     10
1 2025-01-03     20
2 2025-01-04     30
3 2025-01-05     40
4 2025-01-06     50
            Value
2025-01-02     10
2025-01-03     20
2025-01-04     30
2025-01-05     40
2025-01-06     50

            Value
2025-01-03     20
2025-01-04     30
2025-01-05     40

MultiIndexing

In [5]:
import numpy as np
import pandas as pd
arrays=[
    ['North','North','South','South'],
    [2024,2025,2024,2025]
]
index=pd.MultiIndex.from_arrays(arrays,names=('Region','Year'))
df=pd.DataFrame(np.random.randint(100,500,size=(4,2)),index=index,columns=['Product_A','Product_B'])
print(df.index)
print(df.columns)
df

MultiIndex([('North', 2024),
            ('North', 2025),
            ('South', 2024),
            ('South', 2025)],
           names=['Region', 'Year'])
Index(['Product_A', 'Product_B'], dtype='str')

             Product_A  Product_B
Region Year
North  2024        172        496
       2025        483        360
South  2024        441        355
       2025        403        114

In [16]:
# Slicing in Multiindexing
print(df.loc['North'])
print(df.xs('North',level='Region'))
# all region year 2024
print(df.xs(2024,level='Year'))
print(df.xs('Product_A',axis=1))
print(df.xs(('South',2025)))

      Product_A  Product_B
Year
2024        172        496
2025        483        360
      Product_A  Product_B
Year
2024        172        496
2025        483        360
        Product_A  Product_B
Region
North         172        496
South         441        355
Region  Year
North   2024    172
        2025    483
South   2024    441
        2025    403
Name: Product_A, dtype: int32
Product_A    403
Product_B    114
Name: (South, 2025), dtype: int32

Aggregation using MultiIndexing

In [ ]:
print(df.groupby(level='Region').sum())
print(df.groupby(level='Region').mean())
print(df.groupby(level='Year').mean())
print(df.groupby(level='Year').sum())

        Product_A  Product_B
Region
North         655        856
South         844        469
        Product_A  Product_B
Region
North       327.5      428.0
South       422.0      234.5
      Product_A  Product_B
Year
2024      306.5      425.5
2025      443.0      237.0
      Product_A  Product_B
Year
2024        613        851
2025        886        474

In [29]:
df_reset=df.reset_index()
df_reset
df_reset.iloc[1]
df_reset

  Region  Year  Product_A  Product_B
0  North  2024        172        496
1  North  2025        483        360
2  South  2024        441        355
3  South  2025        403        114

Pivot Table

In [33]:
data = {
    'Region': ['North', 'North', 'South', 'South'],
    'Year': [2024, 2025, 2024, 2025],
    'Product': ['Product_A', 'Product_B', 'Product_A', 'Product_B'],
    'Sales': [232, 192, 412, 156]
}
df=pd.DataFrame(data)
pivot=pd.pivot_table(
    df,
    values='Sales',
    index='Region',
    columns='Product',
    aggfunc='sum'
)
pivot

Product  Product_A  Product_B
Region
North          232        192
South          412        156

In [40]:
data = {
    'Gender': ['Male', 'Male', 'Female', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Preference': ['Tea', 'Coffee', 'Coffee', 'Tea', 'Tea', 'Coffee', 'Coffee', 'Tea']
}
df=pd.DataFrame(data)
pivot=pd.pivot_table(
    df,
    index='Gender',
    columns='Preference',
    aggfunc='size'
)
pivot
pd.crosstab(df['Gender'],df['Preference'])

Preference  Coffee  Tea
Gender
Female           2    2
Male             2    2